baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Ian Lumsden'
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  background: /images/site/hardin_valley_dusk_img.jpeg

  # Provide logos for the site
  # logo:
  #   main: /images/site/...
  #   inverted: /images/site/...
  #   favicon: /images/site/...

  baseURL: https://ilumsden.github.io
  gitRepo: https://github.com/ilumsden/ilumsden.github.io
  gitBranch: main

  # specify whether you want to write some blog posts or not
  enableBlogPost: false

  # specify whether you want to show Table of Contents in reading page of Blog
  enableTOC: false

  # specify whether you want the language flags to be displayed.
  showFlags: true

  features:
    portfolio:
      enabled: true
    analytics:
      enabled: false
    newsletter:
      enabled: false
    blog:
      enabled: false
    notes:
      enabled: false
    comment:
      enabled: false

  darkMode:
    provider: darkreader
    enable: true
    default: system

  footer:
    disclaimer:
      enabled: true
    newsletter:
      enable: false
